// Code generated by counterfeiter. DO NOT EDIT.
package promptfakes

import (
	"context"
	"sync"

	"github.com/Carbonfrost/joe-cli/extensions/prompt"
)

type FakePrompter struct {
	ConfirmStub        func(context.Context, string, bool) (bool, error)
	confirmMutex       sync.RWMutex
	confirmArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 bool
	}
	confirmReturns struct {
		result1 bool
		result2 error
	}
	confirmReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	EditStub        func(context.Context, string, string, bool) (string, error)
	editMutex       sync.RWMutex
	editArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 bool
	}
	editReturns struct {
		result1 string
		result2 error
	}
	editReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	InputStub        func(context.Context, string, string) (string, error)
	inputMutex       sync.RWMutex
	inputArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	inputReturns struct {
		result1 string
		result2 error
	}
	inputReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	MultiSelectStub        func(context.Context, string, []string, []string) ([]int, error)
	multiSelectMutex       sync.RWMutex
	multiSelectArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []string
		arg4 []string
	}
	multiSelectReturns struct {
		result1 []int
		result2 error
	}
	multiSelectReturnsOnCall map[int]struct {
		result1 []int
		result2 error
	}
	PasswordStub        func(context.Context, string) (string, error)
	passwordMutex       sync.RWMutex
	passwordArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	passwordReturns struct {
		result1 string
		result2 error
	}
	passwordReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	SelectStub        func(context.Context, string, string, []string) (int, error)
	selectMutex       sync.RWMutex
	selectArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 []string
	}
	selectReturns struct {
		result1 int
		result2 error
	}
	selectReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePrompter) Confirm(arg1 context.Context, arg2 string, arg3 bool) (bool, error) {
	fake.confirmMutex.Lock()
	ret, specificReturn := fake.confirmReturnsOnCall[len(fake.confirmArgsForCall)]
	fake.confirmArgsForCall = append(fake.confirmArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 bool
	}{arg1, arg2, arg3})
	stub := fake.ConfirmStub
	fakeReturns := fake.confirmReturns
	fake.recordInvocation("Confirm", []interface{}{arg1, arg2, arg3})
	fake.confirmMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePrompter) ConfirmCallCount() int {
	fake.confirmMutex.RLock()
	defer fake.confirmMutex.RUnlock()
	return len(fake.confirmArgsForCall)
}

func (fake *FakePrompter) ConfirmCalls(stub func(context.Context, string, bool) (bool, error)) {
	fake.confirmMutex.Lock()
	defer fake.confirmMutex.Unlock()
	fake.ConfirmStub = stub
}

func (fake *FakePrompter) ConfirmArgsForCall(i int) (context.Context, string, bool) {
	fake.confirmMutex.RLock()
	defer fake.confirmMutex.RUnlock()
	argsForCall := fake.confirmArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePrompter) ConfirmReturns(result1 bool, result2 error) {
	fake.confirmMutex.Lock()
	defer fake.confirmMutex.Unlock()
	fake.ConfirmStub = nil
	fake.confirmReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakePrompter) ConfirmReturnsOnCall(i int, result1 bool, result2 error) {
	fake.confirmMutex.Lock()
	defer fake.confirmMutex.Unlock()
	fake.ConfirmStub = nil
	if fake.confirmReturnsOnCall == nil {
		fake.confirmReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.confirmReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakePrompter) Edit(arg1 context.Context, arg2 string, arg3 string, arg4 bool) (string, error) {
	fake.editMutex.Lock()
	ret, specificReturn := fake.editReturnsOnCall[len(fake.editArgsForCall)]
	fake.editArgsForCall = append(fake.editArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 bool
	}{arg1, arg2, arg3, arg4})
	stub := fake.EditStub
	fakeReturns := fake.editReturns
	fake.recordInvocation("Edit", []interface{}{arg1, arg2, arg3, arg4})
	fake.editMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePrompter) EditCallCount() int {
	fake.editMutex.RLock()
	defer fake.editMutex.RUnlock()
	return len(fake.editArgsForCall)
}

func (fake *FakePrompter) EditCalls(stub func(context.Context, string, string, bool) (string, error)) {
	fake.editMutex.Lock()
	defer fake.editMutex.Unlock()
	fake.EditStub = stub
}

func (fake *FakePrompter) EditArgsForCall(i int) (context.Context, string, string, bool) {
	fake.editMutex.RLock()
	defer fake.editMutex.RUnlock()
	argsForCall := fake.editArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakePrompter) EditReturns(result1 string, result2 error) {
	fake.editMutex.Lock()
	defer fake.editMutex.Unlock()
	fake.EditStub = nil
	fake.editReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakePrompter) EditReturnsOnCall(i int, result1 string, result2 error) {
	fake.editMutex.Lock()
	defer fake.editMutex.Unlock()
	fake.EditStub = nil
	if fake.editReturnsOnCall == nil {
		fake.editReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.editReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakePrompter) Input(arg1 context.Context, arg2 string, arg3 string) (string, error) {
	fake.inputMutex.Lock()
	ret, specificReturn := fake.inputReturnsOnCall[len(fake.inputArgsForCall)]
	fake.inputArgsForCall = append(fake.inputArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.InputStub
	fakeReturns := fake.inputReturns
	fake.recordInvocation("Input", []interface{}{arg1, arg2, arg3})
	fake.inputMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePrompter) InputCallCount() int {
	fake.inputMutex.RLock()
	defer fake.inputMutex.RUnlock()
	return len(fake.inputArgsForCall)
}

func (fake *FakePrompter) InputCalls(stub func(context.Context, string, string) (string, error)) {
	fake.inputMutex.Lock()
	defer fake.inputMutex.Unlock()
	fake.InputStub = stub
}

func (fake *FakePrompter) InputArgsForCall(i int) (context.Context, string, string) {
	fake.inputMutex.RLock()
	defer fake.inputMutex.RUnlock()
	argsForCall := fake.inputArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePrompter) InputReturns(result1 string, result2 error) {
	fake.inputMutex.Lock()
	defer fake.inputMutex.Unlock()
	fake.InputStub = nil
	fake.inputReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakePrompter) InputReturnsOnCall(i int, result1 string, result2 error) {
	fake.inputMutex.Lock()
	defer fake.inputMutex.Unlock()
	fake.InputStub = nil
	if fake.inputReturnsOnCall == nil {
		fake.inputReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.inputReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakePrompter) MultiSelect(arg1 context.Context, arg2 string, arg3 []string, arg4 []string) ([]int, error) {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	var arg4Copy []string
	if arg4 != nil {
		arg4Copy = make([]string, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.multiSelectMutex.Lock()
	ret, specificReturn := fake.multiSelectReturnsOnCall[len(fake.multiSelectArgsForCall)]
	fake.multiSelectArgsForCall = append(fake.multiSelectArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []string
		arg4 []string
	}{arg1, arg2, arg3Copy, arg4Copy})
	stub := fake.MultiSelectStub
	fakeReturns := fake.multiSelectReturns
	fake.recordInvocation("MultiSelect", []interface{}{arg1, arg2, arg3Copy, arg4Copy})
	fake.multiSelectMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePrompter) MultiSelectCallCount() int {
	fake.multiSelectMutex.RLock()
	defer fake.multiSelectMutex.RUnlock()
	return len(fake.multiSelectArgsForCall)
}

func (fake *FakePrompter) MultiSelectCalls(stub func(context.Context, string, []string, []string) ([]int, error)) {
	fake.multiSelectMutex.Lock()
	defer fake.multiSelectMutex.Unlock()
	fake.MultiSelectStub = stub
}

func (fake *FakePrompter) MultiSelectArgsForCall(i int) (context.Context, string, []string, []string) {
	fake.multiSelectMutex.RLock()
	defer fake.multiSelectMutex.RUnlock()
	argsForCall := fake.multiSelectArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakePrompter) MultiSelectReturns(result1 []int, result2 error) {
	fake.multiSelectMutex.Lock()
	defer fake.multiSelectMutex.Unlock()
	fake.MultiSelectStub = nil
	fake.multiSelectReturns = struct {
		result1 []int
		result2 error
	}{result1, result2}
}

func (fake *FakePrompter) MultiSelectReturnsOnCall(i int, result1 []int, result2 error) {
	fake.multiSelectMutex.Lock()
	defer fake.multiSelectMutex.Unlock()
	fake.MultiSelectStub = nil
	if fake.multiSelectReturnsOnCall == nil {
		fake.multiSelectReturnsOnCall = make(map[int]struct {
			result1 []int
			result2 error
		})
	}
	fake.multiSelectReturnsOnCall[i] = struct {
		result1 []int
		result2 error
	}{result1, result2}
}

func (fake *FakePrompter) Password(arg1 context.Context, arg2 string) (string, error) {
	fake.passwordMutex.Lock()
	ret, specificReturn := fake.passwordReturnsOnCall[len(fake.passwordArgsForCall)]
	fake.passwordArgsForCall = append(fake.passwordArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.PasswordStub
	fakeReturns := fake.passwordReturns
	fake.recordInvocation("Password", []interface{}{arg1, arg2})
	fake.passwordMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePrompter) PasswordCallCount() int {
	fake.passwordMutex.RLock()
	defer fake.passwordMutex.RUnlock()
	return len(fake.passwordArgsForCall)
}

func (fake *FakePrompter) PasswordCalls(stub func(context.Context, string) (string, error)) {
	fake.passwordMutex.Lock()
	defer fake.passwordMutex.Unlock()
	fake.PasswordStub = stub
}

func (fake *FakePrompter) PasswordArgsForCall(i int) (context.Context, string) {
	fake.passwordMutex.RLock()
	defer fake.passwordMutex.RUnlock()
	argsForCall := fake.passwordArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePrompter) PasswordReturns(result1 string, result2 error) {
	fake.passwordMutex.Lock()
	defer fake.passwordMutex.Unlock()
	fake.PasswordStub = nil
	fake.passwordReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakePrompter) PasswordReturnsOnCall(i int, result1 string, result2 error) {
	fake.passwordMutex.Lock()
	defer fake.passwordMutex.Unlock()
	fake.PasswordStub = nil
	if fake.passwordReturnsOnCall == nil {
		fake.passwordReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.passwordReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakePrompter) Select(arg1 context.Context, arg2 string, arg3 string, arg4 []string) (int, error) {
	var arg4Copy []string
	if arg4 != nil {
		arg4Copy = make([]string, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.selectMutex.Lock()
	ret, specificReturn := fake.selectReturnsOnCall[len(fake.selectArgsForCall)]
	fake.selectArgsForCall = append(fake.selectArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 []string
	}{arg1, arg2, arg3, arg4Copy})
	stub := fake.SelectStub
	fakeReturns := fake.selectReturns
	fake.recordInvocation("Select", []interface{}{arg1, arg2, arg3, arg4Copy})
	fake.selectMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePrompter) SelectCallCount() int {
	fake.selectMutex.RLock()
	defer fake.selectMutex.RUnlock()
	return len(fake.selectArgsForCall)
}

func (fake *FakePrompter) SelectCalls(stub func(context.Context, string, string, []string) (int, error)) {
	fake.selectMutex.Lock()
	defer fake.selectMutex.Unlock()
	fake.SelectStub = stub
}

func (fake *FakePrompter) SelectArgsForCall(i int) (context.Context, string, string, []string) {
	fake.selectMutex.RLock()
	defer fake.selectMutex.RUnlock()
	argsForCall := fake.selectArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakePrompter) SelectReturns(result1 int, result2 error) {
	fake.selectMutex.Lock()
	defer fake.selectMutex.Unlock()
	fake.SelectStub = nil
	fake.selectReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakePrompter) SelectReturnsOnCall(i int, result1 int, result2 error) {
	fake.selectMutex.Lock()
	defer fake.selectMutex.Unlock()
	fake.SelectStub = nil
	if fake.selectReturnsOnCall == nil {
		fake.selectReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.selectReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakePrompter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePrompter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ prompt.Prompter = new(FakePrompter)
