// Code generated by counterfeiter. DO NOT EDIT.
package bindfakes

import (
	"context"
	"sync"

	"github.com/Carbonfrost/joe-cli/extensions/bind"
)

type FakeBinder[T any] struct {
	BindStub        func(context.Context) (T, error)
	bindMutex       sync.RWMutex
	bindArgsForCall []struct {
		arg1 context.Context
	}
	bindReturns struct {
		result1 T
		result2 error
	}
	bindReturnsOnCall map[int]struct {
		result1 T
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBinder[T]) Bind(arg1 context.Context) (T, error) {
	fake.bindMutex.Lock()
	ret, specificReturn := fake.bindReturnsOnCall[len(fake.bindArgsForCall)]
	fake.bindArgsForCall = append(fake.bindArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.BindStub
	fakeReturns := fake.bindReturns
	fake.recordInvocation("Bind", []interface{}{arg1})
	fake.bindMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBinder[T]) BindCallCount() int {
	fake.bindMutex.RLock()
	defer fake.bindMutex.RUnlock()
	return len(fake.bindArgsForCall)
}

func (fake *FakeBinder[T]) BindCalls(stub func(context.Context) (T, error)) {
	fake.bindMutex.Lock()
	defer fake.bindMutex.Unlock()
	fake.BindStub = stub
}

func (fake *FakeBinder[T]) BindArgsForCall(i int) context.Context {
	fake.bindMutex.RLock()
	defer fake.bindMutex.RUnlock()
	argsForCall := fake.bindArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBinder[T]) BindReturns(result1 T, result2 error) {
	fake.bindMutex.Lock()
	defer fake.bindMutex.Unlock()
	fake.BindStub = nil
	fake.bindReturns = struct {
		result1 T
		result2 error
	}{result1, result2}
}

func (fake *FakeBinder[T]) BindReturnsOnCall(i int, result1 T, result2 error) {
	fake.bindMutex.Lock()
	defer fake.bindMutex.Unlock()
	fake.BindStub = nil
	if fake.bindReturnsOnCall == nil {
		fake.bindReturnsOnCall = make(map[int]struct {
			result1 T
			result2 error
		})
	}
	fake.bindReturnsOnCall[i] = struct {
		result1 T
		result2 error
	}{result1, result2}
}

func (fake *FakeBinder[T]) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBinder[T]) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ bind.Binder[any] = new(FakeBinder[any])
